schedule:
- day:
  - class:
    - room: '301'
      subject: Операционные системы
      teacher: Досалиев Дж. А.
      time: 11:30-13:00
      type: Лабораторная
      weeks:
      - 2
      - 4
      - 6
      - 8
      - 10
      - 16
    - room: '301'
      subject: Операционные системы
      teacher: Досалиев Дж. А.
      time: 13:10-14:40
      type: Практика
      weeks:
      - 2
      - 4
      - 6
      - 8
      - 10
      - 16
    name: Среда
  - class: []
    name: Пятница
